name: dart_toolbox
description: A comprehensive Dart package offering a versatile toolbox of utilities, helpers, and extensions to streamline development workflows.
version: 1.2.0+3
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  random_string: ^2.3.1
  recase: ^4.1.0

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
